name: 3. DEMO - Automation Test Workflow - API Cucumber Java
on:
  workflow_dispatch:
jobs:
  regression-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Test run
        run: |
          cd src/api-cucumber-java
          mvn clean test -Dcucumber.options="--tags @regression_qa"

      - name: Upload report artifact
        uses: actions/upload-artifact@v3
        with:
          name: regression-test-api-reports
          path: src/ui-selenium-js/report/Chrome/index.html
          retention-days: 1
