name: 3. DEMO - Automation Test Workflow - API Cucumber Java
on:
  workflow_dispatch:
  name: on-demand
    inputs:
      ENV:
        type: choice
        required: true
        options:
          - DEV
          - QA
          - CT
          - PROD
        default: "QA"
      TEST_TYPE:
          type: choice
          required: true
          options:
            - SMOKE
            - SANITY
            - REGRESSION
jobs:
  regression-test:
    runs-on: ubuntu-latest
    steps:
    run: echo "BDD Tags: @${{ github.event.inputs.TEST_TYPE }}_${{ github.event.inputs.ENV }}"
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Test run
        run: |
          cd src/api-cucumber-java
          mvn clean test -Dcucumber.options="--tags @regression_qa"

      - name: Upload report artifact
        uses: actions/upload-artifact@v3
        with:
          name: regression-test-api-reports
          path: src/api-cucumber-java/target/maven-cucumber-report/cucumber-html-reports
          retention-days: 1
