name: 3. DEMO - Automation Test Workflow - API Cucumber Java
on:
  workflow_dispatch:
    inputs:
      ENV:
        description: 'Environment'
        required: true
        default: 'dev'
        options: ['dev', 'qa', 'ct', 'prod']
      TEST_TYPE:
        description: 'Test Type'
        required: true
        default: 'smoke'
        options: ['smoke', 'sanity', 'regression']

jobs:
  test-summarry:
    runs-on: ubuntu-latest
    steps:
      - name: Show test run information
        run: |
          echo "BDD Tags: @${{ github.event.inputs.TEST_TYPE }}_${{ github.event.inputs.ENV }}"
          
  regression-test:
    needs: test-summarry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Test run
        run: |
          cd src/api-cucumber-java
          mvn clean test -Dcucumber.options="--tags @${{ github.event.inputs.TEST_TYPE }}_${{ github.event.inputs.ENV }}"

      - name: Upload report artifact
        uses: actions/upload-artifact@v3
        with:
          name: regression-test-api-reports
          path: src/api-cucumber-java/target/maven-cucumber-report/cucumber-html-reports
          retention-days: 1
