name: Test Workflow

on:
  workflow_dispatch:
    inputs:
      ENV:
        description: 'Select environment'
        required: true
        default: 'DEV'
        type: choice
        options:
          - DEV
          - QA
          - CT
          - PROD
      TEST_TYPE:
        description: 'Select test type'
        required: true
        default: 'Smoke'
        type: choice
        options:
          - Smoke
          - Sanity
          - Regression
      BROWSER:
        description: 'Select browser'
        required: true
        default: 'Chrome'
        type: choice
        options:
          - Chrome
          - Firefox
          - Edge

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Convert string to uppercase
      run: echo "::set-output name=uppercase::${{inputs.ENV }}${{inputs.TEST_TYPE }}${{inputs.BROWSER }}" | tr '[:lower:]' '[:upper:]'
    
    - name: Convert string to lowercase
      run: echo "::set-output name=lowercase::${{inputs.ENV }}${{inputs.TEST_TYPE }}${{nputs.BROWSER }}" | tr '[:upper:]' '[:lower:]'
