name: Automated Testing Workflow

on:
  workflow_dispatch:
    #2.1 define a workflow_dispatch event with 3 inputs:
    inputs:
      ENV:
        description: 'Environment'
        required: true
        default: 'DEV'
        options: ['DEV', 'QA', 'CT', 'PROD']
      TEST_TYPE:
        description: 'Test Type'
        required: true
        default: 'Smoke'
        options: ['Smoke', 'Sanity', 'Regression']
      BROWSER:
        description: 'Browser'
        required: true
        default: 'Chrome'
        options: ['Chrome', 'Firefox', 'Edge']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Convert string to uppercase/lowercase
        run: |
          echo "${{ inputs.ENV }}" | tr '[:upper:]' '[:lower:]'
          echo "${{ inputs.TEST_TYPE }}" | tr '[:lower:]' '[:upper:]'
          echo "${{ inputs.BROWSER }}" | tr '[:lower:]' '[:upper:]'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.16'

      - name: Setup Browser
        if: ${{inputs.BROWSER == 'Chrome' }}
        uses: browser-actions/setup-chrome@v1

      - name: Setup Browser
        if: ${{inputs.BROWSER == 'Firefox' }}
        uses: browser-actions/setup-firefox@v1

      - name: Setup Browser
        if: ${{inputs.BROWSER == 'Edge' }}
        uses: browser-actions/setup-edge@v1

